import {
  User,
  Listing,
  Order,
  Review,
  Conversation,
  Message,
  Dispute,
  Transaction,
  Flag,
  CategoryRecord,
  PaymentMethod,
  NotificationItem,
} from "./types";

const avatar = (seed: string) => `https://i.pravatar.cc/150?u=${seed}`;
const img = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?w=800&h=600&fit=crop`;

export const CURRENT_IDS = {
  buyer: "u-jordan",
  seller: "u-mystic",
  admin: "u-admin",
  support: "u-support",
};

export const users: User[] = [
  {
    id: "u-jordan",
    name: "Jordan Ellery",
    email: "jordan.ellery@example.com",
    avatarUrl: avatar("jordan"),
    roles: ["Buyer"],
    verificationStatus: "Verified",
    accountStatus: "Active",
    joinDate: "2024-02-11",
    country: "United States",
    bio: "PC gamer, mostly tactical shooters and MMOs.",
    totalOrdersAsBuyer: 3,
    totalSpent: 143.5,
  },
  {
    id: "u-mystic",
    name: "MysticVendor22",
    email: "mysticvendor22@example.com",
    avatarUrl: avatar("mystic"),
    roles: ["Seller"],
    verificationStatus: "Verified",
    accountStatus: "Active",
    rating: 4.8,
    reviewCount: 214,
    joinDate: "2022-06-03",
    country: "Germany",
    bio: "Trusted account & currency seller since 2022. Instant delivery on most items.",
    responseTime: "Usually replies in under 10 minutes",
    online: true,
    totalSalesAsSeller: 214,
    totalEarned: 18420.75,
  },
  {
    id: "u-priya",
    name: "Priya Kapoor",
    email: "priya.kapoor@example.com",
    avatarUrl: avatar("priya"),
    roles: ["Buyer", "Seller"],
    verificationStatus: "Pending",
    accountStatus: "Active",
    rating: 4.6,
    reviewCount: 38,
    joinDate: "2023-11-20",
    country: "India",
    totalOrdersAsBuyer: 2,
    totalSpent: 62.5,
    totalSalesAsSeller: 38,
    totalEarned: 1120,
  },
  {
    id: "u-nightowl",
    name: "NightOwlBoosts",
    email: "nightowlboosts@example.com",
    avatarUrl: avatar("nightowl"),
    roles: ["Seller"],
    verificationStatus: "Verified",
    accountStatus: "Active",
    rating: 4.9,
    reviewCount: 501,
    joinDate: "2021-09-14",
    country: "Canada",
    bio: "Rank boosting specialist — LoL, Valorant, Apex. GM-level players only.",
    responseTime: "Usually replies in under 30 minutes",
    online: false,
    totalSalesAsSeller: 501,
    totalEarned: 42310,
  },
  {
    id: "u-shadow",
    name: "ShadowFlip99",
    email: "shadowflip99@example.com",
    avatarUrl: avatar("shadow"),
    roles: ["Seller"],
    verificationStatus: "Unverified",
    accountStatus: "Banned",
    rating: 2.1,
    reviewCount: 19,
    joinDate: "2024-08-01",
    country: "Unknown",
    totalSalesAsSeller: 19,
    totalEarned: 340,
  },
  {
    id: "u-admin",
    name: "Alicia Moreno",
    email: "alicia.moreno@gametrade.com",
    avatarUrl: avatar("alicia"),
    roles: ["Admin"],
    verificationStatus: "Verified",
    accountStatus: "Active",
    joinDate: "2021-01-05",
    country: "United States",
  },
  {
    id: "u-support",
    name: "Alex R.",
    email: "alex.r@gametrade.com",
    avatarUrl: avatar("alexr"),
    roles: ["Support"],
    verificationStatus: "Verified",
    accountStatus: "Active",
    joinDate: "2022-04-18",
    country: "United Kingdom",
  },
  {
    id: "u-quickflip",
    name: "QuickFlipper",
    email: "quickflipper@example.com",
    avatarUrl: avatar("quickflipper"),
    roles: ["Seller"],
    verificationStatus: "Verified",
    accountStatus: "Active",
    rating: 3.9,
    reviewCount: 12,
    joinDate: "2025-01-09",
    country: "Brazil",
    totalSalesAsSeller: 12,
    totalEarned: 540,
  },
  {
    id: "u-unknown42",
    name: "UnknownUser42",
    email: "unknownuser42@example.com",
    avatarUrl: avatar("unknown42"),
    roles: ["Buyer"],
    verificationStatus: "Unverified",
    accountStatus: "Active",
    joinDate: "2026-08-22",
    country: "Unknown",
  },
];

export const categories: CategoryRecord[] = [
  { id: "c-accounts", name: "Accounts", commissionRate: 10, active: true, listingCount: 3 },
  { id: "c-currency", name: "Currency", commissionRate: 8, active: true, listingCount: 2 },
  { id: "c-boosting", name: "Boosting", commissionRate: 12, active: true, listingCount: 1 },
  { id: "c-items", name: "Items", commissionRate: 10, active: true, listingCount: 0 },
  { id: "c-topup", name: "Top-up", commissionRate: 5, active: true, listingCount: 0 },
];

export const listings: Listing[] = [
  {
    id: "l-valorant-immortal",
    title: "Valorant Immortal 2 Account — Full Access",
    category: "Accounts",
    game: "Valorant",
    description:
      "Full-access Immortal 2 account with email change available. 40+ skins including 3 knife skins, all agents unlocked, level 210.",
    price: 89,
    deliveryMethod: "Instant",
    status: "Active",
    views: 3420,
    wishlistedCount: 212,
    sellerId: "u-mystic",
    imageUrls: [img("1542751371-adc38448a05e"), img("1493711662062-fa541adb3fc8")],
    createdAt: "2026-08-02",
    specs: { Rank: "Immortal 2", Region: "NA", Level: "210", "Included skins": "42" },
  },
  {
    id: "l-wow-gold",
    title: "WoW Gold — 50,000g (Stormrage)",
    category: "Currency",
    game: "World of Warcraft",
    description:
      "50,000 gold delivered via in-game mail trade on Stormrage-US. Safe, no bots, split into batches on request.",
    price: 34.5,
    deliveryMethod: "Manual 1hr",
    status: "Active",
    views: 1876,
    wishlistedCount: 64,
    sellerId: "u-nightowl",
    imageUrls: [img("1552820728-8b83bb6b773f")],
    createdAt: "2026-09-01",
    specs: { Server: "Stormrage (US)", "Amount available": "500,000g" },
    currencyAmountAvailable: 500000,
  },
  {
    id: "l-lol-boost",
    title: "League of Legends Placement Boost (5 games)",
    category: "Boosting",
    game: "League of Legends",
    description:
      "Duo or solo placement boost, 5 games, played by a GM-level booster. VPN protected, off-hours available.",
    price: 22,
    deliveryMethod: "Manual 24hr",
    status: "Active",
    views: 998,
    wishlistedCount: 31,
    sellerId: "u-nightowl",
    imageUrls: [img("1538481199705-c710c4e965fc")],
    createdAt: "2026-08-20",
    specs: {
      "Current rank": "Any",
      "Desired rank": "Varies",
      "Estimated completion time": "24-48 hours",
    },
  },
  {
    id: "l-fortnite-skins",
    title: "Fortnite Rare Skin Bundle Account",
    category: "Accounts",
    game: "Fortnite",
    description:
      "OG account with Renegade Raider, Black Knight, Skull Trooper. Full email access included.",
    price: 54,
    deliveryMethod: "Instant",
    status: "Pending review",
    views: 140,
    wishlistedCount: 9,
    sellerId: "u-priya",
    imageUrls: [img("1550745165-9bc0b252726f")],
    createdAt: "2026-09-20",
    specs: { Rank: "N/A", Region: "EU", Level: "142", "Included skins": "18" },
  },
  {
    id: "l-ffxiv-gil",
    title: "FFXIV Gil — 10M (Aether)",
    category: "Currency",
    game: "Final Fantasy XIV",
    description: "10 million Gil, Aether data center. Delivered via retainer or market board flip.",
    price: 28,
    deliveryMethod: "Manual 1hr",
    status: "Paused",
    views: 512,
    wishlistedCount: 18,
    sellerId: "u-mystic",
    imageUrls: [img("1591370874773-6702e8f12fd8")],
    createdAt: "2026-07-15",
    specs: { Server: "Aether", "Amount available": "40,000,000g" },
    currencyAmountAvailable: 40000000,
  },
  {
    id: "l-apex-account",
    title: "Apex Legends Predator Account — Season Ready",
    category: "Accounts",
    game: "Apex Legends",
    description: "Predator badge history, all legends unlocked, heirloom shards banked.",
    price: 149,
    deliveryMethod: "Instant",
    status: "Active",
    views: 2210,
    wishlistedCount: 128,
    sellerId: "u-quickflip",
    imageUrls: [img("1580327344181-c1163234e5a0")],
    createdAt: "2026-09-10",
    specs: { Rank: "Predator", Region: "NA", Level: "310", "Included skins": "27" },
  },
  {
    id: "l-wow-boost",
    title: "Mythic+ Dungeon Boost (Weekly Vault)",
    category: "Boosting",
    game: "World of Warcraft",
    description: "Piloted or self-play M+ boost, guaranteed weekly vault item level.",
    price: 45,
    deliveryMethod: "Manual 24hr",
    status: "Rejected",
    views: 4,
    wishlistedCount: 0,
    sellerId: "u-shadow",
    imageUrls: [img("1607853202273-797f1c22a38e")],
    createdAt: "2026-09-22",
    moderationReason: "Listing images did not match the described service.",
    specs: { "Current rank": "N/A", "Desired rank": "N/A", "Estimated completion time": "1 week" },
  },
];

export const orders: Order[] = [
  {
    id: "o-1001",
    listingId: "l-valorant-immortal",
    buyerId: "u-jordan",
    sellerId: "u-mystic",
    amount: 89,
    commission: 8.9,
    status: "Completed",
    placedDate: "2026-09-10",
    escrowHolder: "Seller paid",
  },
  {
    id: "o-1002",
    listingId: "l-wow-gold",
    buyerId: "u-priya",
    sellerId: "u-nightowl",
    amount: 34.5,
    commission: 2.76,
    quantity: 50000,
    status: "Pending",
    placedDate: "2026-09-24",
    escrowHolder: "Platform escrow",
  },
  {
    id: "o-1003",
    listingId: "l-lol-boost",
    buyerId: "u-jordan",
    sellerId: "u-nightowl",
    amount: 22,
    commission: 2.64,
    status: "Disputed",
    placedDate: "2026-09-21",
    escrowHolder: "Platform escrow",
  },
  {
    id: "o-1004",
    listingId: "l-ffxiv-gil",
    buyerId: "u-priya",
    sellerId: "u-mystic",
    amount: 28,
    commission: 2.24,
    quantity: 10000000,
    status: "Delivered",
    placedDate: "2026-09-23",
    escrowHolder: "Platform escrow",
    deliveryNotes: "Sent via retainer — check mail on Aether server.",
  },
];

export const reviews: Review[] = [
  {
    id: "r-1",
    orderId: "o-1001",
    authorId: "u-jordan",
    subjectId: "u-mystic",
    rating: 5,
    comment: "Fast delivery, account exactly as described.",
    date: "2026-09-11",
  },
  {
    id: "r-2",
    orderId: "o-1004",
    authorId: "u-priya",
    subjectId: "u-nightowl",
    rating: 4,
    comment: "Good boost, took a bit longer than estimated.",
    date: "2026-08-30",
  },
  {
    id: "r-3",
    orderId: "o-1003",
    authorId: "u-jordan",
    subjectId: "u-shadow",
    rating: 2,
    comment: "Slow to respond, had to open a dispute.",
    date: "2026-09-05",
    sellerReply: "We're sorry about the delay — refund was issued.",
  },
];

export const conversations: Conversation[] = [
  {
    id: "conv-1",
    participantIds: ["u-jordan", "u-mystic"],
    relatedOrderId: "o-1001",
    relatedListingId: "l-valorant-immortal",
    lastMessageAt: "2026-09-25T05:10:00Z",
  },
  {
    id: "conv-2",
    participantIds: ["u-priya", "u-nightowl"],
    relatedOrderId: "o-1002",
    relatedListingId: "l-wow-gold",
    lastMessageAt: "2026-09-24T18:00:00Z",
  },
  {
    id: "conv-3",
    participantIds: ["u-jordan", "u-support"],
    relatedOrderId: "o-1003",
    supportThread: true,
    lastMessageAt: "2026-09-25T06:50:00Z",
  },
  {
    id: "conv-4",
    participantIds: ["u-priya", "u-support"],
    supportThread: true,
    lastMessageAt: "2026-09-25T04:00:00Z",
  },
];

export const messages: Message[] = [
  {
    id: "m-1",
    conversationId: "conv-1",
    senderId: "u-jordan",
    text: "Hey! Just bought the Immortal 2 account, when can I expect delivery?",
    timestamp: "2026-09-10T14:00:00Z",
  },
  {
    id: "m-2",
    conversationId: "conv-1",
    senderId: "u-mystic",
    text: "Thanks for the order! Sending login details over now, give me 5 minutes.",
    timestamp: "2026-09-10T14:03:00Z",
  },
  {
    id: "m-3",
    conversationId: "conv-1",
    senderId: "u-mystic",
    text: "Delivered! Check your inbox for login details.",
    timestamp: "2026-09-10T14:09:00Z",
  },
  {
    id: "m-4",
    conversationId: "conv-2",
    senderId: "u-priya",
    text: "Can you start the boost tonight?",
    timestamp: "2026-09-24T18:00:00Z",
  },
  {
    id: "m-5",
    conversationId: "conv-3",
    senderId: "u-jordan",
    text: "My boost order still isn't done after 3 days.",
    timestamp: "2026-09-25T06:50:00Z",
  },
  {
    id: "m-6",
    conversationId: "conv-4",
    senderId: "u-priya",
    text: "Hi, I wanted to ask about verification times.",
    timestamp: "2026-09-25T04:00:00Z",
  },
];

export const disputes: Dispute[] = [
  {
    id: "d-1",
    orderId: "o-1003",
    reason: "Not delivered",
    buyerDetails: "It's been 3 days and I haven't seen any progress on my rank.",
    sellerResponse: "",
    internalNotes: [],
    status: "Under review",
    openedDate: "2026-09-22",
  },
];

export const transactions: Transaction[] = [
  {
    id: "t-1",
    userId: "u-jordan",
    type: "Purchase",
    amount: -89,
    status: "Completed",
    date: "2026-09-10",
    description: "Valorant Immortal 2 Account",
  },
  {
    id: "t-2",
    userId: "u-mystic",
    type: "Payout",
    amount: 79.5,
    commission: 8.9,
    status: "Processing",
    date: "2026-09-24",
    method: "Bank transfer",
  },
  {
    id: "t-3",
    userId: "u-priya",
    type: "Top-up",
    amount: 50,
    status: "Completed",
    date: "2026-09-15",
    method: "PayPal",
  },
  {
    id: "t-4",
    userId: "u-jordan",
    type: "Purchase",
    amount: -22,
    status: "Completed",
    date: "2026-09-21",
    description: "League of Legends Placement Boost",
  },
];

export const flags: Flag[] = [
  {
    id: "f-1",
    userId: "u-shadow",
    type: "Price anomaly",
    severity: "High",
    status: "New",
    detectedDate: "2026-09-23",
    detail: "Listing priced 90% below category median for identical spec set.",
  },
  {
    id: "f-2",
    userId: "u-unknown42",
    type: "Multiple failed logins",
    severity: "Medium",
    status: "New",
    detectedDate: "2026-09-24",
    detail: "6 failed login attempts within 10 minutes from 3 distinct IP ranges.",
  },
  {
    id: "f-3",
    userId: "u-quickflip",
    type: "Rapid listing creation",
    severity: "Low",
    status: "Reviewed",
    detectedDate: "2026-09-18",
    detail: "9 listings created within a single hour.",
  },
];

export const paymentMethods: PaymentMethod[] = [
  { id: "pm-1", userId: "u-jordan", label: "Visa", masked: "•••• 4242", isDefault: true },
  { id: "pm-2", userId: "u-jordan", label: "PayPal", masked: "jordan.e@example.com", isDefault: false },
];

export const notifications: NotificationItem[] = [
  {
    id: "n-1",
    userId: "u-jordan",
    type: "order",
    text: "Your order for FFXIV Gil — 10M was delivered.",
    timestamp: "2026-09-23T09:00:00Z",
    read: false,
    linkOrderId: "o-1004",
  },
  {
    id: "n-2",
    userId: "u-jordan",
    type: "message",
    text: "Support replied in your dispute conversation.",
    timestamp: "2026-09-25T06:55:00Z",
    read: false,
    linkConversationId: "conv-3",
  },
  {
    id: "n-3",
    userId: "u-jordan",
    type: "promo",
    text: "Weekend sale: up to 15% off Boosting services.",
    timestamp: "2026-09-20T09:00:00Z",
    read: true,
    linkCategory: "Boosting",
  },
  {
    id: "n-4",
    userId: "u-jordan",
    type: "order",
    text: "Your Valorant account order was completed and rated.",
    timestamp: "2026-09-11T09:00:00Z",
    read: true,
    linkOrderId: "o-1001",
  },
];

export const heroSlides = [
  { id: "hs-1", title: "Weekend Sale: 15% off Boosting", category: "Boosting" as const, image: img("1538481199705-c710c4e965fc") },
  { id: "hs-2", title: "Fresh Valorant Accounts, Instant Delivery", category: "Accounts" as const, image: img("1542751371-adc38448a05e") },
  { id: "hs-3", title: "Top up your favorite game currency", category: "Currency" as const, image: img("1552820728-8b83bb6b773f") },
];

export const categoryTiles: { name: string; category: (typeof listings)[number]["category"]; game?: string }[] = [
  { name: "Valorant", category: "Accounts", game: "Valorant" },
  { name: "World of Warcraft", category: "Currency", game: "World of Warcraft" },
  { name: "League of Legends", category: "Boosting", game: "League of Legends" },
  { name: "Fortnite", category: "Accounts", game: "Fortnite" },
  { name: "Final Fantasy XIV", category: "Currency", game: "Final Fantasy XIV" },
  { name: "Currency Top-up", category: "Top-up" },
];

export const cannedResponses = [
  "Please allow 24-48 hours for delivery.",
  "Thanks for reaching out — could you share your order ID?",
  "I've escalated this to the seller, we'll update you shortly.",
  "Your refund has been processed and should reflect within 3-5 business days.",
];
